[package]
name = "cognite"
version = "0.1.0"
authors = ["Haakon Garseg Mørk <haakon.mork@cognite.com>"]
publish = false
edition = "2018"

[dependencies]
reqwest = { version = "0.10.0-alpha.2", features = ["json"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
uuid = "0.7.4"
futures = "0.3"